### ISSUE TITLE
URL Shortener for meeting logs [Feature Request]

### ISSUE THREAD

**Issue by thunderbirdtr** [t0xic0der/fragment#18]
Current meeting log URL is a bit long and also make QR code complex as well. If we add URL shortener and generate a QR based on that would make QR simple make URL easier as well.

**Comment by t0xic0der** [comment]
As the repository has been moved to https://github.com/fedora-infra/mote/tree/fragment, this issue has been transferred to fedora-infra/mote#169 and is no longer tracked here.
