### ISSUE TITLE
Add relevant links in the footer

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/fragment#24]
Like the one at https://getfedora.org/.

![Screenshot from 2021-08-30 21-04-08](https://user-images.githubusercontent.com/49605954/131365114-84e0de41-e864-4d49-b3ee-9fea259baaf3.png)

**Comment by sakkshm26** [comment]
@t0xic0der Hey, I want to work on this issue. Can you please specify the links which need to be added in the footer?

**Comment by t0xic0der** [comment]
The links being mentioned about here are identical to the ones that you'd find on the footer of https://getfedora.org/ as specified in the ticket body. Do you want me to assign this ticket to you?

**Comment by sakkshm26** [comment]
Yes.

**Comment by t0xic0der** [comment]
As the repository has been moved to https://github.com/fedora-infra/mote/tree/fragment, this issue has been transferred to fedora-infra/mote#170 and is no longer tracked here.
