### ISSUE TITLE
Rework the design with faint gray gradient to fit with Fedora aesthetics

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/fragment#25]
For instance

![1](https://user-images.githubusercontent.com/49605954/131433323-42e745b5-f24c-4139-ab2c-8550aca52fc9.png)

**Comment by RajshreeVats** [comment]
new to open source. can I be assigned to do the required enhancement?

**Comment by t0xic0der** [comment]
I would suggest connecting with folks from Fedora Design (here, https://pagure.io/design) and working with their guidance. Once you have connected with them and they approve of your involvement, I would assign you this ticket.

**Comment by t0xic0der** [comment]
As the repository has been moved to https://github.com/fedora-infra/mote/tree/fragment, this issue has been transferred to fedora-infra/mote#171 and is no longer tracked here.
