### ISSUE TITLE
Investigate packaging of the software in an RPM

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/fragment#26]
Check on the feasibility and viability of the packaging.

**Comment by thunderbirdtr** [comment]
I would like to work on this

**Comment by t0xic0der** [comment]
The packaging scheme would be a lot different from the one that we had for Mote - pretty much in the lines of https://github.com/t0xic0der/supervisor-frontend-service/blob/master/svfrontend.spec but with PyProject macros. I am assigning this to you.

**Comment by t0xic0der** [comment]
As the repository has been moved to https://github.com/fedora-infra/mote/tree/fragment, this issue has been transferred to fedora-infra/mote#172 and is no longer tracked here.
