### ISSUE TITLE
Create custom 404 page

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/fragment#39]
Create custom 404 page

**Comment by Chetana16032002** [comment]
**html:**
<div id="main">
    	<div class="fof">
        		<h1>Error 404</h1>
    	</div>
</div>

**css:**

*{
    transition: all 0.6s;
}

html {
    height: 100%;
}

body{
    font-family: 'Lato', sans-serif;
    color: #888;
    margin: 0;
}

#main{
    display: table;
    width: 100%;
    height: 100vh;
    text-align: center;
}

.fof{
	  display: table-cell;
	  vertical-align: middle;
}

.fof h1{
	  font-size: 50px;
	  display: inline-block;
	  padding-right: 12px;
	  animation: type .5s alternate infinite;
}

@keyframes type{
	  from{box-shadow: inset -3px 0px 0px #888;}
	  to{box-shadow: inset -3px 0px 0px transparent;}
}

**Comment by t0xic0der** [comment]
@Chetana16032002,

I'm not really sure what it is that you wish to convey with the CSS snippet.

**Comment by Chetana16032002** [comment]
add your html boiler plate , css link 
like :

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <link rel="stylesheet" href="index.css">
    <div id="main">
        	<div class="fof">
            		<h1>Error 404</h1>
        	</div>
    </div>
  </body>
</html>

**Comment by Chetana16032002** [comment]
<link rel="stylesheet" href="index.css">
in the body of css
`

**Comment by t0xic0der** [comment]
As the repository has been moved to https://github.com/fedora-infra/mote/tree/fragment, this issue has been transferred to fedora-infra/mote#176 and is no longer tracked here.
