### ISSUE TITLE
Implement searching in each modal screens

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/fragment#9]
Search needs to be implemented in

- [ ] Channel modal
- [ ] Date modal
- [ ] Meeting modal
- [ ] Maybe in-conversation searching for meeting logs and minutes

**Comment by Kadermiyanyedi** [comment]
I would like to work on this

**Comment by t0xic0der** [comment]
Sure, @Kadermiyanyedi. I am assigning you this issue.

**Comment by Kadermiyanyedi** [comment]
It is expected to be completed within 2 weeks. I couldn't update Milestone.

**Comment by mugiwarafx** [comment]
Hi! We will work together in this issue. many thanks!

**Comment by t0xic0der** [comment]
As the repository has been moved to https://github.com/fedora-infra/mote/tree/fragment, this issue has been transferred to fedora-infra/mote#168 and is no longer tracked here.

**Comment by t0xic0der** [comment]
@mugiwarafx @Kadermiyanyedi,

Please visit fedora-infra/mote#168 and request assignment there.
